export const metadata = {
  title: 'About Us page',
  description: 'About Us page generated by create next app',
}

export default function AboutUsLayout({children}) {
    return (
        <section>
            {children}
        </section>
    )
}